
spring.application.name=scentia-store

#Para definir el formato de despliegue de fecha/hora del log en la consola
logging.pattern.dateformat=hh:mm

#Para eliminar mensajes invasivos de Spring
spring.main.banner-mode=off

#En desarrollo el "cache" del servidor (false), en producción "true"
spring.thymeleaf.cache=false

#Conexión local a la BD Techshop en MySQL
#spring.datasource.url=jdbc:mysql://localhost:3306/scentia_store
spring.datasource.url=jdbc:mysql://scentia-store-06-c3gamer-172d.j.aivencloud.com:19200/scentia_store
# ── Base de datos MySQL ──────────────────────────────────────────────────────

spring.datasource.username=grupo6
spring.datasource.password=12345

#Driver y plataforma de comunicación
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#mostrar información en el log
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.type.descriptor.sql.BasicBinder=TRACE

#Esta información se utiliza para obtener acceso a su storage.
firebase.bucket.name=techshop-65f4e.firebasestorage.app
firebase.storage.path=techshop
firebase.json.path=firebase
firebase.json.file=techshop-65f4e-firebase-adminsdk-fbsvc-e91e451c4a.json
